package com.arthur.project.dataObject;

public class BookBaseDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_base.book_no
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    private Integer bookNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_base.book_id
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    private String bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_base.book_name
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_base.book_writer
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    private String bookWriter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_base.book_public
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    private String bookPublic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_base.book_page
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    private String bookPage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_base.book_detail
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    private String bookDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_base.book_number
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    private String bookNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_base.book_no
     *
     * @return the value of book_base.book_no
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public Integer getBookNo() {
        return bookNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_base.book_no
     *
     * @param bookNo the value for book_base.book_no
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public void setBookNo(Integer bookNo) {
        this.bookNo = bookNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_base.book_id
     *
     * @return the value of book_base.book_id
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_base.book_id
     *
     * @param bookId the value for book_base.book_id
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_base.book_name
     *
     * @return the value of book_base.book_name
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_base.book_name
     *
     * @param bookName the value for book_base.book_name
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_base.book_writer
     *
     * @return the value of book_base.book_writer
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public String getBookWriter() {
        return bookWriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_base.book_writer
     *
     * @param bookWriter the value for book_base.book_writer
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public void setBookWriter(String bookWriter) {
        this.bookWriter = bookWriter == null ? null : bookWriter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_base.book_public
     *
     * @return the value of book_base.book_public
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public String getBookPublic() {
        return bookPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_base.book_public
     *
     * @param bookPublic the value for book_base.book_public
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public void setBookPublic(String bookPublic) {
        this.bookPublic = bookPublic == null ? null : bookPublic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_base.book_page
     *
     * @return the value of book_base.book_page
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public String getBookPage() {
        return bookPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_base.book_page
     *
     * @param bookPage the value for book_base.book_page
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public void setBookPage(String bookPage) {
        this.bookPage = bookPage == null ? null : bookPage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_base.book_detail
     *
     * @return the value of book_base.book_detail
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public String getBookDetail() {
        return bookDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_base.book_detail
     *
     * @param bookDetail the value for book_base.book_detail
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public void setBookDetail(String bookDetail) {
        this.bookDetail = bookDetail == null ? null : bookDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_base.book_number
     *
     * @return the value of book_base.book_number
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public String getBookNumber() {
        return bookNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_base.book_number
     *
     * @param bookNumber the value for book_base.book_number
     *
     * @mbg.generated Wed Mar 16 18:42:14 GMT+08:00 2022
     */
    public void setBookNumber(String bookNumber) {
        this.bookNumber = bookNumber;
    }
}