package com.arthur.project.dataObject;

public class BookDetailDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.detail_no
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    private Integer detailNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.detail_base
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    private Integer detailBase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.detail_id
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    private String detailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.detail_state
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    private String detailState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_detail.detail_lend
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    private Integer detailLend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.detail_no
     *
     * @return the value of book_detail.detail_no
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    public Integer getDetailNo() {
        return detailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.detail_no
     *
     * @param detailNo the value for book_detail.detail_no
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    public void setDetailNo(Integer detailNo) {
        this.detailNo = detailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.detail_base
     *
     * @return the value of book_detail.detail_base
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    public Integer getDetailBase() {
        return detailBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.detail_base
     *
     * @param detailBase the value for book_detail.detail_base
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    public void setDetailBase(Integer detailBase) {
        this.detailBase = detailBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.detail_id
     *
     * @return the value of book_detail.detail_id
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    public String getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.detail_id
     *
     * @param detailId the value for book_detail.detail_id
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    public void setDetailId(String detailId) {
        this.detailId = detailId == null ? null : detailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.detail_state
     *
     * @return the value of book_detail.detail_state
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    public String getDetailState() {
        return detailState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.detail_state
     *
     * @param detailState the value for book_detail.detail_state
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    public void setDetailState(String detailState) {
        this.detailState = detailState == null ? null : detailState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_detail.detail_lend
     *
     * @return the value of book_detail.detail_lend
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    public Integer getDetailLend() {
        return detailLend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_detail.detail_lend
     *
     * @param detailLend the value for book_detail.detail_lend
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    public void setDetailLend(Integer detailLend) {
        this.detailLend = detailLend;
    }
}