package com.arthur.project.dataObject;

import java.util.Date;

public class LendDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lend.lend_no
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    private Integer lendNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lend.lend_book_no
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    private Integer lendBookNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lend.lend_user_no
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    private Integer lendUserNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lend.lend_time
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    private Date lendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lend.lend_return_time
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    private String lendReturnTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lend.lend_no
     *
     * @return the value of lend.lend_no
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    public Integer getLendNo() {
        return lendNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lend.lend_no
     *
     * @param lendNo the value for lend.lend_no
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    public void setLendNo(Integer lendNo) {
        this.lendNo = lendNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lend.lend_book_no
     *
     * @return the value of lend.lend_book_no
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    public Integer getLendBookNo() {
        return lendBookNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lend.lend_book_no
     *
     * @param lendBookNo the value for lend.lend_book_no
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    public void setLendBookNo(Integer lendBookNo) {
        this.lendBookNo = lendBookNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lend.lend_user_no
     *
     * @return the value of lend.lend_user_no
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    public Integer getLendUserNo() {
        return lendUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lend.lend_user_no
     *
     * @param lendUserNo the value for lend.lend_user_no
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    public void setLendUserNo(Integer lendUserNo) {
        this.lendUserNo = lendUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lend.lend_time
     *
     * @return the value of lend.lend_time
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    public Date getLendTime() {
        return lendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lend.lend_time
     *
     * @param lendTime the value for lend.lend_time
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    public void setLendTime(Date lendTime) {
        this.lendTime = lendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lend.lend_return_time
     *
     * @return the value of lend.lend_return_time
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    public String getLendReturnTime() {
        return lendReturnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lend.lend_return_time
     *
     * @param lendReturnTime the value for lend.lend_return_time
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    public void setLendReturnTime(String lendReturnTime) {
        this.lendReturnTime = lendReturnTime == null ? null : lendReturnTime.trim();
    }
}