package com.arthur.project.dao;

import com.arthur.project.dataObject.BookDetailDO;

import java.util.List;

public interface BookDetailDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Integer detailNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    int insert(BookDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    int insertSelective(BookDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    BookDetailDO selectByPrimaryKey(Integer detailNo);

    List<BookDetailDO> selectByBase(Integer detailBase);

    BookDetailDO selectByBookId(String bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(BookDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_detail
     *
     * @mbg.generated Wed Mar 16 18:42:40 GMT+08:00 2022
     */
    int updateByPrimaryKey(BookDetailDO record);
}