package com.arthur.project.dao;

import com.arthur.project.dataObject.LendDO;

import java.util.List;

public interface LendDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Integer lendNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    int insert(LendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    int insertSelective(LendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    LendDO selectByPrimaryKey(Integer lendNo);

    List<LendDO> selectAll();

    List<LendDO> selectByUserNo(Integer lendUserDo);

    LendDO selectByBookNo(Integer bookNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(LendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lend
     *
     * @mbg.generated Wed Mar 16 18:42:59 GMT+08:00 2022
     */
    int updateByPrimaryKey(LendDO record);
}