package com.arthur.project.dao;

import com.arthur.project.dataObject.UserDO;
import org.apache.catalina.User;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 14 21:50:21 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 14 21:50:21 GMT+08:00 2022
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 14 21:50:21 GMT+08:00 2022
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 14 21:50:21 GMT+08:00 2022
     */
    UserDO selectByPrimaryKey(Integer userId);

    UserDO selectByName(String userName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 14 21:50:21 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 14 21:50:21 GMT+08:00 2022
     */
    int updateByPrimaryKey(UserDO record);
}